name: PR Comment and Update with Append or Replace from File
author: Ethan Graf <ethan.graf@fuzzbuzz.io>
description: Leaves a comment on an open PR based on the contents of a file. If a comment with the right prefix exists, update instead. 
branding:
  icon: 'message-square'  
  color: 'black'
inputs:
  path: 
    description: file path
    required: true
  prefix:
    description: comment prefix
    required: true
  action:
    description: control behavior on update can be append or replace (default append)
    required: false
    default: append
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
    - ${{ inputs.prefix }}
    - ${{ inputs.action }}
